version: '3'
services: 
    app:
        container_name: graphqlfirst
        restart: always
        build: .
        ports:
            - '80:3000'
        links:
            - db  
    db:
        container_name: bygoadwv:K3zKb5UZ-nYk3mAevW1LQtPHRpBNIUzT@rajje.db.elephantsql.com
        image: postgres
        ports: 
            - '5432:5432'