version: '3'
services: 
    app:
        container_name: graphqlfirst
        restart: always
        build: .
        ports:
            - '80:3000'
        links:
            - db  
    db:
        container_name: bygoadwv
        image: postgres
        ports: 
            - '5433:5432'